---
driver:
  name: docker
  <% if (RUBY_PLATFORM =~ /darwin/) %>
  socket: <%= "#{ENV['DOCKER_HOST']}" %>
  docker_path: /usr/local/bin/docker
  <% else %>
  docker_path: /usr/bin/docker'
  <% end %>
  forward_agent: true
  require_chef_omnibus: 12.3
  disable_upstart: false
  use_cache: false
  remove_images: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      name: vagrant
    run_list:
      - recipe[jlsolrcloud::default]
    attributes:
     jlsolrcloud:
       # Normally set zkhosts in a wrapper cookbook
       zkhosts:
         - host1:2181
         - host2:2181
 # This suite is run on a private jenkins server
  - name: jenkins
    run_list:
      - recipe[jlsolrcloud::default]
    attributes:
     jlsolrcloud:
       # Normally set zkhosts in a wrapper cookbook
       zkhosts:
         - zookeeper:2181
    # As defined in docker-compose.yml
    driver:
      links:
        - chefjlsolrcloud_zookeeper_1:zookeeper
