Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - '.kitchen/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
    - 'Berksfile'
